version: "2"
run:
  tests: true
  allow-parallel-runners: true

# Enable formatters explicitly. None is enabled by default
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

linters:
  # Enable specific linters in addition to defaults
  enable:
     # Core Safety & Correctness
    - nilerr      # Finds code that returns nil even if it checks that the error is not nil

    # Style & Consistency
    - misspell    # Finds commonly misspelled English words
    - revive      # Fast, configurable, extensible, flexible, and drop-in replacement for golint
    - errorlint   # Go 1.13+ error wrapping support
    - prealloc    # Finds slice declarations that could potentially be pre-allocated
    - gocritic    # Provides diagnostics that check for bugs, performance and style issues

    # Complexity & Code Quality
    - gocognit    # Computes and checks the cognitive complexity of functions

    # Security
    - gosec       # Inspects source code for security problems

    # Testing & Concurrency
    - testifylint # Checks usage of github.com/stretchr/testify
    - tparallel   # Detects inappropriate usage of t.Parallel() method in your Go test codes

  settings:
    revive:
      enable-default-rules: true
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
