version: "2"
run:
  tests: true
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - dupword
    - embeddedstructfieldcheck
    - err113
    - errorlint
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gosmopolitan
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: UK
    nolintlint:
      require-specific: true
    prealloc:
      for-loops: true
    revive:
      rules:
        - name: exported
          disabled: true
        - name: context-as-argument
          disabled: false
    wrapcheck:
      ignore-package-globs:
        - golang.org/x/sync/errgroup
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/utilitywarehouse/tflint-ruleset-kafka)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
