# pin to the version specified in go.mod to avoid inconsistent behaviour
# on systems that have an older version of Go installed
default_language_version:
  golang: 1.23.0
repos:
-   repo: https://github.com/golangci/golangci-lint
    rev: v2.2.1
    hooks:
    -   id: golangci-lint-full
    -   id: golangci-lint-config-verify
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
-   repo: https://github.com/segmentio/golines
    rev: v0.12.2
    hooks:
      - id: golines
        args: ["--max-len", "120"]
