# pin to the version specified in go.mod to avoid inconsistent behaviour
# on systems that have an older version of Go installed
default_language_version:
  golang: 1.22.0
repos:
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
    -   id: golangci-lint-full
    -   id: golangci-lint-config-verify
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
